### ISSUE TITLE
Parallelizing analyzeDuprates

### ISSUE THREAD

**Issue by tiagochst** [ssayols/dupRadar#2]
Hello, 

I am using dupRadar in a nextflow pipeline and one of the bottleneck is dupradar which is taking 14 hours to run.

I was checking the code and you are using the `lapply` base function
https://github.com/ssayols/dupRadar/blob/master/R/analyzeDuprates.R#L75-L89

You could use the `plyr::alply` to speed up it performing the code in parallel.
I use it in my code if https://github.com/tiagochst/ELMER/blob/master/R/Main_function.R#L268-L281

I was just wondering if there was any reason why it is not parallelized, such as the amount of  memory used. Or maybe you tried and it was slower.

Thanks!

**Comment by ssayols** [comment]
Hi @tiagochst 
if you profile the `lapply` chunk that you highlight, you'll see it takes just a few seconds (probably even less than a second) to run for the standard scenario. With standard scenario I mean something that looks like the examples in the package vignette (an RNAseq experiment with ~20k genes).

Anyways, I agree it may benefit from parallel execution, and translating it into an `parallel::mclapply()` call would be trivial. I take note of this.

Back to your issue. The part that takes most of dupRadar execution is going through the bam file and counting reads on features (we internally call `Rsubread::featureCounts()`. See [lines 41-52 in analyzeDuprates.R](https://github.com/ssayols/dupRadar/blob/4af85dc57f43568cefbd02823adc859635ae99de/R/analyzeDuprates.R#L41)). If dupRadar takes ~14h to run and your scenario is close enough to the "standard" scenario I described above, the reason is probably that your input bam files are not sorted as expected. If you have single-end data, sort by coordinate. If you have paire-end data, featureCounts expects (and in extension, dupRadar) to have your reads sorted by fragment position: position + mate read next to it. This is something that samtools cannot do (AFAIK), thus one has to use the `repair` tool from the Rsubread/Subread package before calling dupRadar.

cheers,
Sergi

**Comment by tiagochst** [comment]
Hi @ssayols,

If it just take seconds there is no reason to  parallelize it. 

I'll recheck the pipeline with the nf-core team, probably the bam is not sorted as you pointed. Thank you for the explanation!
